name: "Docker Login"
description: "Authenticate to Docker Hub"
runs:
  using: "composite"
  steps:
    - name: Log in to Docker Hub
      shell: bash
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
