name: "setup-and-load-env"
description: "Setup and load environment variables"
inputs:
  DOCKER_USERNAME:
    description: "DOCKER_USERNAME from environment"
    required: true
  PACKAGE_NAME:
    description: "PACKAGE_NAME from environment"
    required: true
  PACKAGE_VERSION:
    description: "PACKAGE_VERSION from environment"
    required: true
  EMAIL:
    description: "EMAIL from environment"
    required: true
  IMAGE_TAG:
    description: "IMAGE_TAG from environment"
    required: true
  DATABASE_URL:
    description: "DATABASE_URL from environment"
    required: true
  PORT:
    description: "PORT from environment"
    required: true
  JWT_SECRET:
    description: "JWT_SECRET from environment"
    required: true
  JWT_REFRESH_SECRET:
    description: "JWT_REFRESH_SECRET from environment"
    required: true
  JWT_ACCESS_EXPIRE:
    description: "JWT_ACCESS_EXPIRE from environment"
    required: true
  JWT_REFRESH_EXPIRE:
    description: "JWT_REFRESH_EXPIRE from environment"
    required: true
  GOOGLE_CLIENT_ID:
    description: "GOOGLE_CLIENT_ID from environment"
    required: true
  GOOGLE_CLIENT_SECRET:
    description: "GOOGLE_CLIENT_SECRET from environment"
    required: true
  FACEBOOK_CLIENT_ID:
    description: "FACEBOOK_CLIENT_ID from environment"
    required: true
  FACEBOOK_CLIENT_SECRET:
    description: "FACEBOOK_CLIENT_SECRET from environment"
    required: true
  FRONTEND_URL:
    description: "FRONTEND_URL from environment"
    required: true
  EMAIL_USER:
    description: "EMAIL_USER from environment"
    required: true
  EMAIL_PASS:
    description: "EMAIL_PASS from environment"
    required: true
  TWILIO_ACCOUNT_SID:
    description: "TWILIO_ACCOUNT_SID from environment"
    required: true
  TWILIO_AUTH_TOKEN:
    description: "TWILIO_AUTH_TOKEN from environment"
    required: true
  TWILIO_PHONE_NUMBER:
    description: "TWILIO_PHONE_NUMBER from environment"
    required: true
  STRIPE_SECRET:
    description: "STRIPE_SECRET from environment"
    required: true
  STRIPE_WEBHOOK_SECRET:
    description: "STRIPE_WEBHOOK_SECRET from environment"
    required: true
  CLOUDINARY_CLOUD_NAME:
    description: "CLOUDINARY_CLOUD_NAME from environment"
    required: true
  CLOUDINARY_API_KEY:
    description: "CLOUDINARY_API_KEY from environment"
    required: true
  CLOUDINARY_API_SECRET:
    description: "CLOUDINARY_API_SECRET from environment"
    required: true
  SE_DOCKER_PASSWORD:
    description: "SE_DOCKER_PASSWORD from environment"
    required: true
  SE_GIT_TOKEN:
    description: "SE_GIT_TOKEN from environment"
    required: true
  VPS_HOST:
    description: "VPS_HOST from environment"
    required: true
  VPS_USER:
    description: "VPS_USER from environment"
    required: true
  VPS_HOST_IP:
    description: "VPS_HOST_IP from environment"
    required: true
runs:
  using: "composite"
  steps:
    - name: Generate .env
      shell: bash
      run: |
        ENV_FILE="$GITHUB_WORKSPACE/.env"
        {
          echo "DOCKER_USERNAME=${{ inputs.DOCKER_USERNAME }}"
          echo "PACKAGE_NAME=${{ inputs.PACKAGE_NAME }}"
          echo "PACKAGE_VERSION=${{ inputs.PACKAGE_VERSION }}"
          echo "EMAIL=${{ inputs.EMAIL }}"
          echo "IMAGE_TAG=${{ inputs.IMAGE_TAG }}"
          echo "DATABASE_URL=${{ inputs.DATABASE_URL }}"
          echo "PORT=${{ inputs.PORT }}"
          echo "JWT_SECRET=${{ inputs.JWT_SECRET }}"
          echo "JWT_REFRESH_SECRET=${{ inputs.JWT_REFRESH_SECRET }}"
          echo "JWT_ACCESS_EXPIRE=${{ inputs.JWT_ACCESS_EXPIRE }}"
          echo "JWT_REFRESH_EXPIRE=${{ inputs.JWT_REFRESH_EXPIRE }}"
          echo "GOOGLE_CLIENT_ID=${{ inputs.GOOGLE_CLIENT_ID }}"
          echo "GOOGLE_CLIENT_SECRET=${{ inputs.GOOGLE_CLIENT_SECRET }}"
          echo "FACEBOOK_CLIENT_ID=${{ inputs.FACEBOOK_CLIENT_ID }}"
          echo "FACEBOOK_CLIENT_SECRET=${{ inputs.FACEBOOK_CLIENT_SECRET }}"
          echo "FRONTEND_URL=${{ inputs.FRONTEND_URL }}"
          echo "EMAIL_USER=${{ inputs.EMAIL_USER }}"
          echo "EMAIL_PASS=${{ inputs.EMAIL_PASS }}"
          echo "TWILIO_ACCOUNT_SID=${{ inputs.TWILIO_ACCOUNT_SID }}"
          echo "TWILIO_AUTH_TOKEN=${{ inputs.TWILIO_AUTH_TOKEN }}"
          echo "TWILIO_PHONE_NUMBER=${{ inputs.TWILIO_PHONE_NUMBER }}"
          echo "STRIPE_SECRET=${{ inputs.STRIPE_SECRET }}"
          echo "STRIPE_WEBHOOK_SECRET=${{ inputs.STRIPE_WEBHOOK_SECRET }}"
          echo "CLOUDINARY_CLOUD_NAME=${{ inputs.CLOUDINARY_CLOUD_NAME }}"
          echo "CLOUDINARY_API_KEY=${{ inputs.CLOUDINARY_API_KEY }}"
          echo "CLOUDINARY_API_SECRET=${{ inputs.CLOUDINARY_API_SECRET }}"
          echo "SE_DOCKER_PASSWORD=${{ inputs.SE_DOCKER_PASSWORD }}"
          echo "SE_GIT_TOKEN=${{ inputs.SE_GIT_TOKEN }}"
          echo "VPS_HOST=${{ inputs.VPS_HOST }}"
          echo "VPS_USER=${{ inputs.VPS_USER }}"
          echo "VPS_HOST_IP=${{ inputs.VPS_HOST_IP }}"
        } > "$ENV_FILE"
        if [[ -n "${{ inputs.VPS_SSH_PRIVATE_KEY }}" ]]; then
          echo "${{ inputs.VPS_SSH_PRIVATE_KEY }}" > "$GITHUB_WORKSPACE/deploy_key.pem"
          chmod 600 "$GITHUB_WORKSPACE/deploy_key.pem"
          echo "VPS_SSH_PRIVATE_KEY_FILE=$GITHUB_WORKSPACE/deploy_key.pem" >> "$ENV_FILE"
        fi
        echo "✅ Environment file created"
